* Git基础

** 设置Git
安装成功后，需要进行设置：
#+BEGIN_EXAMPLE
$ git config --global user.name "Your Name"
$ git config --global user.email "myemail@example.com"
#+END_EXAMPLE

** 创建仓库(repository)
1.创建目录
#+BEGIN_EXAMPLE
$ mkdir mygit
$ cd mygit
#+END_EXAMPLE

2.把目录变成仓库
#+BEGIN_EXAMPLE
$ git init
Initialized empty Git repository in /Users/michael/learngit/.git/
#+END_EXAMPLE

** 使用Git
1.在仓库目录中创建文件，

2.把文件添加到仓库暂存区
#+BEGIN_EXAMPLE
$ git add file.txt
#+END_EXAMPLE

3.把暂存区文件提交到当前分支
#+BEGIN_EXAMPLE
$ git commit -m "about describle"
#+END_EXAMPLE
关于git commit命令，-m后面输入的是本次提交的说明，可以任意内容，最好是有意义的。

一次可以提交多个文件：
#+BEGIN_EXAMPLE
$ git add file1.txt file2.txt file3.txt
$ git commit -m "add three files"
#+END_EXAMPLE

** 回退
查看提交日志
git log
查看简单日志信息，加 =--pretty=oneline= 参数。

* 远程仓库
** 添加远程库
使用远程仓库Github，由于本地Git仓库和GitHub仓库之间的传输是通过SSH加密的，所以需要一点设置：

1.创建SSH Key
#+BEGIN_EXAMPLE
$ ssh-keygen -t rsa -C "myemail@example.com"
#+END_EXAMPLE
邮件地址使用自己的邮件地址，然后一路回车，使用默认值即可。

2.在Github增加SSH Key
登陆GitHub，打开“Account settings”，“SSH and GPG Keys”页面。
然后，点“New SSH Key”，填上任意Title，在Key文本框里粘贴id_rsa.pub文件的内容，点“Add key”。

3.在Github创建新仓库
在Github的右上角选择“New repository”，创建一个新的仓库。

4.本地关联远程库
在本地仓库运行下面命令：
#+BEGIN_EXAMPLE
git remote add origin https://github.com/username/mygit.git
#+END_EXAMPLE

5.推送本地库内容到远程库
#+BEGIN_EXAMPLE
$ git push -u origin master
#+END_EXAMPLE

6.本地提交
以后，只要本地作了提交，就可以通过命令把本地master分支的最新修改推送至GitHub
#+BEGIN_EXAMPLE
$ git push origin master
#+END_EXAMPLE

** 从远程库克隆
1.克隆本地库
#+BEGIN_EXAMPLE
git clone https://github.com/whoowy/security.git
#+END_EXAMPLE

* Q&A
** 中文文件名乱码
在shell中输入：
#+BEGIN_EXAMPLE
git config --global core.quotepath false
#+END_EXAMPLE
